FROM node:23-alpine

WORKDIR /app

RUN apk add --no-cache wget libc6-compat

COPY package.json package-lock.json* ./
RUN npm ci

EXPOSE 3000


CMD ["npm", "run", "dev", "--", "--hostname", "0.0.0.0", "--port", "3000"]