// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using incident_service.Contexts;

#nullable disable

namespace incident_service.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250225105523_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("incident_service.Models.Incident", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CreationDate");

                    b.Property<int>("Dislike")
                        .HasColumnType("int")
                        .HasColumnName("Dislike");

                    b.Property<double>("Latitude")
                        .HasColumnType("double")
                        .HasColumnName("Latitude");

                    b.Property<int>("Like")
                        .HasColumnType("int")
                        .HasColumnName("Like");

                    b.Property<double>("Longitude")
                        .HasColumnType("double")
                        .HasColumnName("Longitude");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Type");

                    b.HasKey("Id");

                    b.ToTable("Incident");
                });
#pragma warning restore 612, 618
        }
    }
}
