FROM mcr.microsoft.com/dotnet/sdk:8.0

WORKDIR /app

RUN apt-get update && apt-get install -y wget && rm -rf /var/lib/apt/lists/*

COPY *.csproj ./
RUN dotnet restore

COPY . ./

EXPOSE 8080

ENV ASPNETCORE_URLS=http://+:8080
CMD ["dotnet", "watch", "run", "--urls", "http://0.0.0.0:8080", "--no-restore"]